version: "3"
services:
  develop:
    build: .
    container_name: converter-develop
    environment:
      NODE_ENV: dev
      GATEWAY_URL: http://mymachine:9000
      PORT: 4100
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/converter/app
