version: "3"
services:
  test:
    build: .
    container_name: converter-test
    environment:
      PORT: 7658
      NODE_ENV: test
      HOST_IP: 127.0.0.1
      GATEWAY_URL: http://127.0.0.1:9000
      MICROSERVICE_TOKEN: cttoken
      FASTLY_ENABLED: "false"
    command: test
