version: "3"
services:
  test:
    build: .
    container_name: converter-test
    environment:
      PORT: 7658
      NODE_ENV: test
      HOST_IP: 127.0.0.1
      CT_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:7658
      CT_REGISTER_MODE: auto
      API_VERSION: v1
    command: test
