apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
    app: rw
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "4100"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:4100
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 4100

      restartPolicy: Always
